"""empty message

Revision ID: 34e479dd0ab5
Revises: c0d692fa548d
Create Date: 2020-04-12 18:53:21.477903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e479dd0ab5'
down_revision = 'c0d692fa548d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('soil_moisture', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readings', 'soil_moisture')
    # ### end Alembic commands ###
