"""empty message

Revision ID: 66a7d2a57df3
Revises: 34e479dd0ab5
Create Date: 2020-04-18 17:02:33.860490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a7d2a57df3'
down_revision = '34e479dd0ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('pump_status', sa.Float(), nullable=True))
    op.add_column('readings', sa.Column('water_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readings', 'water_level')
    op.drop_column('readings', 'pump_status')
    # ### end Alembic commands ###
