"""empty message

Revision ID: c0d692fa548d
Revises: 
Create Date: 2020-04-12 13:13:22.704789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d692fa548d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baro_temp', sa.Float(), nullable=True),
    sa.Column('baro_pressure', sa.Float(), nullable=True),
    sa.Column('cpu_temp', sa.Float(), nullable=True),
    sa.Column('humid_temp', sa.Float(), nullable=True),
    sa.Column('humid_humid', sa.Float(), nullable=True),
    sa.Column('light', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    # ### end Alembic commands ###
